sm8150-common: Add missing TouchCompanion
error: vendor/lenovo/sm8150-common/Android.bp:1616:1: libhbtpclient depends on undefined module vendor.qti.hardware.improvetouch.touchcompanion@1.0.
Change-Id: I5b56a00b4d76f133bd4e6b7b009a0c5f354eb2c6